name: Publish hiearch-dinit to PyPI

on:
    push:
        tags:
            - 'dinit-*'

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - run: cd generators/hiearch_dinit && make install_release_deps
            - env:
                TWINE_USERNAME: __token__
                TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
              run: cd generators/hiearch_dinit && make upload_pypi
